### ISSUE TITLE
Can't login on latest version or the version before

### ISSUE THREAD

**Issue by ogkimra** [itszechs/DriveStream#70]
![Screenshot_20221207-132332_WhatsApp.png](https://user-images.githubusercontent.com/32086892/206120365-68eab7a3-a6de-4fa6-b7a9-e4cfa46ee385.png)

**Comment by itszechs** [comment]
The login works on latest version [`1.2.2`](https://github.com/itszechs/DriveStream/tree/1.2.2).

Judging from the screenshot that's a [`ChromeCustomTab`](https://developer.chrome.com/docs/android/custom-tabs/) which was removed in v1.2.2 (https://github.com/itszechs/DriveStream/commit/fc541218b747312dfcb88c632a5fb0f47c614ea8).

Please update to v1.2.2 and try again.


Note: Due to change of signing key previous version needs to be uninstalled to install v1.2.2, read the notes on the release.
