### ISSUE TITLE
Scaling & Media Player

### ISSUE THREAD

**Issue by SwordKing69** [itszechs/DriveStream#98]
Hi zech, the recent update was quite good but I didn't saw a major improvement which was continuously demanded by the users and that is you still didn't solved issue regarding subtitles scaling.
Whenever we stream any video file and turn on the subtitles and fill the screen ratio to FILL then the subtitles don't get adjust a little above automatically instead they just stays over a fixed position and after filling screen they just get hide down or say crop out the screen and I am unable yo to watch subtitles and it's really such a big issue.

One more thing I want to tell that if there is a good player like MPV then why are you providing option of EXO player which is written along with (Experimental) tag. Just leave it as it is and remove this experimental thing we don't want that we are satisfied with MPV player. Instead you can think on providing option to open any video file from any external player (If possible).
That's all what I wanna say to you as a a feedback. Hope you will look into this. 💯

**Comment by itszechs** [comment]
https://github.com/mpv-player/mpv/issues/11705#issuecomment-1564290774

This should do the trick, will add as an optional settings (not enforce by default)

**Comment by itszechs** [comment]
Upon further testing `--sub-ass-force-margins=yes` doesn't seem to make any difference, though the [dynamic-crop.lua](https://github.com/Ashyni/mpv-scripts/blob/master/dynamic-crop.lua) does, but not sure if I like the results.

| Original  | dynamic-crop.lua|
|--------|--------|
| ![Screenshot_1706959119](https://github.com/itszechs/DriveStream/assets/52543663/9bdbb4c2-dc79-4dbc-946e-ab19315e3a5e) | ![Screenshot_1706959375](https://github.com/itszechs/DriveStream/assets/52543663/f3ee2c9f-3f61-455b-a8ba-d290fcb6cd3f) |

If I can find a way to dynamically load/unload this lua script and not make it a default behavior, I'd add this but otherwise, it will do more harm than good. 

@SwordKing69

**Comment by itszechs** [comment]
This feature will be added if/when its added in [mpv](https://github.com/mpv-player/mpv)
